domain:
  name: code
  shift: extreme
  tasks:
    code_completion:
      dataset: code_search_net
      dataset_config: python
      split_train: train
      split_val: validation
      split_test: test
      metrics: [pass_at_1, bleu]
      type: generative
      input_col: func_code_tokens
      target_col: func_code_tokens
    docstring_classification:
      dataset: code_search_net
      dataset_config: python
      split_train: train
      split_val: validation
      split_test: test
      metrics: [accuracy]
      type: discriminative
      input_col: func_documentation_tokens
      target_col: language
